const employees = [
           {id:1,
           Icon:require('./assets/emp4.png'),
           Name:'島侑奈',
           Organization1:'DXIC',
        //    Organization2:'',
        //    Organization3:'情報システム部',
        //    Organization4:'業務システムGr',
        //    Organization5:'',
           Post         :'専門職',
           Startdate    :'2014/04/01',
           ITSS1        :'UX Designer',
           ITSS1level   :'4',
           ITSS2        :'',
           ITSS2level   :'',
           Skill        :'UXデザイナー,DX,DX推進,運用設計,給与計算,年末調整,採用,勤務管理,ベンダー管理,ワークフロー,Sharepoint,Intramart',
           Career1      :'2014年4月NSSOL入社',
           Career2      :'2014年4月～10月新人研修',
           Career3      :'2014年8月流通ソリューション事業部配属',
           Career4      :'2014年9月～2020年3月 大手小売業向け基幹システム保守',
           Career5      :'2020年3月～現在　DXIC スクラムラボ　デザイナー',
           Career6      :'',
           Career7      :'',
           Career8      :'',
           Career9      :'',
           Career10     :'',
           Book1image   :require('./assets/datamodel.png'),
           Book1point   :'★★★★★',
           Book1comment :'ためになりました！',
           Book2image   :require('./assets/vendar.png'),
           Book2point   :'★★★★☆',
           Book2comment :'参考になりました。',
           Book3image   :'',
           Book3point   :'',
           Book3comment :'',
           Book4image   :'',
           Book4point   :'',
           Book4comment :'',
           Book5image   :'',
           Book5point   :'',
           Book5comment :'',
           }
           ]
  export default employees