const employee = [
           {id:1,
           icon:require('./assets/employee1.png'),
           Name:'多田 孝和',
           Organization1:'技術本部',
           Organization2:'',
           Organization3:'情報システム部',
           Organization4:'業務システムGr',
           Organization5:'',
           Post         :'上級専門職',
           Startdate    :'2020/03/01',
           ITSS1        :'Project Manager',
           ITSS1level   :'4',
           ITSS2        :'Application Specialist',
           ITSS2level   :'4',
           Skill        :'プロジェクトマネージメント','マネージメント','データ連携','運用設計','給与計算','年末調整','タレントマネージメント','勤務管理','ベンダー管理','ワークフロー','Sharepoint',
                         'Intramart',
           Career1      :'2010年4月商社系Sier入社',
           Career2      :'2010年4月～8月新人研修',
           Career3      :'2010年8月DataSpider検証',
           Career4      :'2010年9月～2011年3月 Lotus Notes8.5.2 マイグレーションプロジェクト　新機能検証・推進',
           Career5      :'・',
           Career6      :'2014年7月会社統合',
           Career7      :'・',
           Career8      :'2017年1月～2020年3月メガバンク向け人事・給与システム保守プロジェクト　賞与・人事資格Tリーダー、ツールTリーダー、データ連携プロジェクトリーダー',
           Career9      :'2020年3月NSSOL入社',
           Career10     :'2020年3月～現在　勤務管理・経費WFシステム刷新プロジェクト　移行・運用リーダー',
           Book1image   :require('./assets/datamodel.png'),
           Book1point   :'★★★★★',
           Book1comment :'実務上のケースでこのようにデータモデリングすればよいという具体的でとてもわかりやすい本',
           Book2image   :require('./assets/vendar.png'),
           Book2point   :'★★★★',
           Book2comment :'遅延していた場合、どのようなアクションをとればいいまで記載されている現場重視の本',
           Book3image   :,
           Book3point   :'★★★★★',
           Book3comment :,
           Book4image   :,
           Book4point   :,
           Book4comment :,
           Book5image   :,
           Book5point   :,
           Book5comment :,
           }
           ]
  export default books